"""Shared frozen dataclasses for the M1 pipeline — the contract all three implementation groups code against (rebuild/M1-PLAN.md section 5).

The plan freezes `Height`, `CellId`, `Settled`, and `ResolvedSpec` verbatim; the spec-side types under `ResolvedSpec` (Rune, Stance, Surface, rows, policy records) and the two cross-group artifacts the plan names (`CellPlan` from surface.resolve_cell, `GlyphRecord` from geometry.realize) live here too, because every group reads or writes them. Any change to this module is a cross-group coordination event.

The adjustments grammar (the `CellId.adjustments` tokens, generated by settlement and consumed by geometry) is part of this contract: `locked` (the ZWNJ chokepoint twin — entry side severed), `en-ext-N` / `ex-ext-N` (same-row connector lengthening by N pixels on the named side), `en-con-N` / `ex-con-N` (the contract inverse), `en-trim-N` / `ex-trim-N` (receiver-side same-row ink blanking with the anchor deliberately left in place — the convention-exempt case), and `en-bind-<bitmap>` / `ex-bind-<bitmap>` (a `bind:` contract substituting a named hand-drawn sibling). Tokens are ordered, generated, never authored.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Collection, Literal, Mapping

Height = str  # "baseline" | "x-height" | "y6" | "top" (registry-validated)

NONE_STATE = "none"
WITHDRAWN_SUFFIX = "-withdrawn"

RIGHT_WINDOW_SLOTS = 4  # right1..rightN, the raw window settlement sees; table.py asserts its Transition/Rule arity against this at import, so a chain-cap raise without the matching table widening fails loudly instead of baking records past the window in silently
RIGHT_CHAIN_CAP = (
    RIGHT_WINDOW_SLOTS - 1
)  # then:/except-carried hops past the immediate right neighbor that spec_load's lint admits — derived, never set independently of the window


@dataclass(frozen=True, slots=True)
class CellId:
    rune: str  # family name (ligatures are ordinary runes)
    stance: str
    entry: Height | None
    exit: Height | None
    adjustments: tuple[str, ...] = ()  # ordered, generated: ("en-ext-1",), ("locked",), () — never authored


@dataclass(frozen=True, slots=True)
class Settled:
    cell: CellId
    seam: Height | None  # the committed seam toward the next position
    extension: int  # summed connector pixels carried on this seam by this side


@dataclass(frozen=True)
class Provenance:
    file: str
    path: str

    def __str__(self) -> str:
        return f"{self.file}:{self.path}"


@dataclass(frozen=True)
class Condition:
    """One side of a `when:` — the closed static vocabulary of design section 3.4. Axis values are tuples even when authored as scalars; empty tuple means the axis is unconstrained."""

    family: tuple[str, ...] = ()
    klass: tuple[str, ...] = ()  # predicate classes or rune-local groups ("class:" in YAML)
    stance: tuple[str, ...] = ()
    joined_at: Height | None = None  # the height of the join being decided; "none" = the seam did not join
    stroke: str | None = None
    is_token: str | None = None  # "boundary" | "space" | "zwnj" | "namer-dot" ("is:" in YAML)
    except_: tuple["Condition", ...] = ()
    then: "Condition | None" = None  # right-only static hop, lint-capped chain; forbidden on refuse/require


@dataclass(frozen=True)
class When:
    left: Condition | None = None
    right: Condition | None = None
    self_entry: str | None = None  # "live" | "none"
    self_exit: str | None = None
    word: str | None = None  # "initial" | "medial" | "final" | "isolated"
    feature: str | None = None


@dataclass(frozen=True)
class Stub:
    """Same-row attachment ink at a side's anchor row. `inks_when` names the liveness state in which the columns are inked (design section 3.2): `inks_when: joined` means a connector nub that is blank in the base drawing and inks exactly when the side joins; `inks_when: withdrawn` is the opposite polarity, ink that retracts on joining (the qsGay case)."""

    cols: tuple[int, ...]
    inks_when: str  # "joined" | "withdrawn"


@dataclass(frozen=True)
class SurfaceRow:
    """One entry or exit row: a height, an anchor x, and the optional bindings/scopes/oddities."""

    height: Height
    x: int
    stroke: str | None = None
    joined: str | None = None  # named sibling bitmap used when this side is live
    joined_x: int | None = None  # per-row anchor override that travels with the joined binding
    withdrawal: str | None = None  # named sibling bitmap, or "safe" (compiler-verified no reaching ink)
    stub: Stub | None = None
    scope: tuple[Condition, ...] = ()  # `from:` on entries, `toward:` on exits; empty = unscoped
    selectable: bool = True  # False carries today's entry_curs_only (GPOS parity only)
    ink_y: int | None = None  # carries today's exit_ink_y row-scan fallback
    x_off_convention: bool = False
    provenance: Provenance | None = None


@dataclass(frozen=True)
class Pairing:
    entry: str  # a height or "none"
    exit: str


@dataclass(frozen=True)
class Pairings:
    never: tuple[Pairing, ...] = ()
    only: tuple[Pairing, ...] | None = None


@dataclass(frozen=True)
class CellBinding:
    """An explicit `cells:` row: the named composition when side bindings touch one cell. `entry`/`exit` are state tokens: a height, a height plus "-withdrawn", or "none"."""

    entry: str
    exit: str
    bitmap: str
    entry_x: int | None = None
    exit_x: int | None = None
    provenance: Provenance | None = None


@dataclass(frozen=True)
class Unlock:
    feature: str
    entry: Height | None = None
    exit: Height | None = None
    pairing: Pairing | None = None
    when: When | None = None
    why: str | None = None
    provenance: Provenance | None = None


@dataclass(frozen=True)
class Surface:
    entries: Mapping[Height, SurfaceRow] = field(default_factory=dict)
    exits: Mapping[Height, SurfaceRow] = field(default_factory=dict)
    pairings: Pairings = field(default_factory=Pairings)
    cells: tuple[CellBinding, ...] = ()
    unlocks: tuple[Unlock, ...] = ()
    require: tuple[str, ...] = ()  # ("entry",) / ("exit",) for join-born stances


@dataclass(frozen=True)
class Bitmap:
    rows: tuple[str, ...]
    y_offset: int = 0

    @property
    def width(self) -> int:
        return max((len(row) for row in self.rows), default=0)

    def row_for_y(self, y: int) -> str | None:
        """The bitmap row at glyph-space y, or None when y is outside the drawing."""
        index = len(self.rows) - 1 - (y - self.y_offset)
        if 0 <= index < len(self.rows):
            return self.rows[index]
        return None


@dataclass(frozen=True)
class Stance:
    name: str
    motion: str
    traits: tuple[str, ...] = ()
    bitmap: Bitmap = field(default_factory=lambda: Bitmap(()))
    bitmaps: Mapping[str, Bitmap] = field(default_factory=dict)
    surface: Surface = field(default_factory=Surface)


@dataclass(frozen=True)
class PolicyRecord:
    """One rider: refuse | prefer | extend | contract | resolve, in the single grammatical shape of design section 3.3. `id` makes a record addressable by a resolve's `against:`; `against`/`pick`/`migrated` are the resolve kind's own fields (design section 5.8, the against-a-named-record slice)."""

    kind: str
    when: When = field(default_factory=When)
    id: str | None = None
    stance: str | None = None
    entry: Height | None = None
    exit: Height | None = None
    cell: Mapping[str, str] | None = None  # cell-grain prefer target
    over: Mapping[str, str] | None = None
    mode: str | None = None  # prefer: "yields-to-joins" (default) | "absolute"
    by: int | None = None
    ok: tuple[int, int] | None = None
    bind: str | None = None
    trim: int | None = None
    split: tuple[int, int] | None = None
    against: tuple[str, str | None] | None = None  # (rune, record id) the resolve arbitrates against
    pick: Mapping[str, str] | None = (
        None  # the winning cell pattern (or {stance: ...}) at the conflicted window
    )
    migrated: str | None = None
    why: str | None = None
    provenance: Provenance | None = None


@dataclass(frozen=True)
class Policy:
    order: tuple[str, ...] = ()
    refuse: tuple[PolicyRecord, ...] = ()
    prefer: tuple[PolicyRecord, ...] = ()
    extend: tuple[PolicyRecord, ...] = ()
    contract: tuple[PolicyRecord, ...] = ()
    resolve: tuple[PolicyRecord, ...] = ()
    groups: Mapping[str, frozenset[str]] = field(default_factory=dict)  # membership resolved by spec_load


@dataclass(frozen=True)
class Rune:
    name: str
    codepoint: int | None = None
    sequence: tuple[str, ...] | None = None  # ligature runes declare this instead of a codepoint
    ductus: Mapping[str, str] = field(default_factory=dict)  # motion name -> hand-drawing prose
    notes: str | None = None
    mono: Bitmap | None = None
    stances: Mapping[str, Stance] = field(default_factory=dict)
    policy: Policy = field(default_factory=Policy)

    @property
    def default_stance(self) -> str:
        if self.policy.order:
            return self.policy.order[0]
        return next(iter(self.stances))


@dataclass(frozen=True)
class BoundaryToken:
    codepoint: int
    splits_runs: bool


@dataclass(frozen=True)
class FeatureInfo:
    kind: str  # "capability" | "taste"
    description: str = ""
    overlay: str | None = None


@dataclass(frozen=True)
class FamilyInfo:
    codepoint: int | None = None
    sequence: tuple[str, ...] | None = None


@dataclass(frozen=True)
class ScriptRegistry:
    heights: Mapping[Height, int] = field(default_factory=dict)
    boundary_tokens: Mapping[str, BoundaryToken] = field(default_factory=dict)
    features: Mapping[str, FeatureInfo] = field(default_factory=dict)
    interactions: tuple[tuple[str, ...], ...] = ()
    predicate_classes: Mapping[str, frozenset[str]] = field(default_factory=dict)  # membership resolved
    families: Mapping[str, FamilyInfo] = field(default_factory=dict)

    def y_of(self, height: Height) -> int:
        return self.heights[height]


@dataclass(frozen=True)
class ResolvedSpec:  # spec_load's output; the input to everything else
    runes: Mapping[str, Rune]  # only the modeled runes
    registry: ScriptRegistry


@dataclass(frozen=True)
class CellPlan:
    """surface.resolve_cell's output: binding resolution only, no ink. `bitmap` is the named sibling the cell renders with (None = the stance's base drawing); anchor x values are post-override; `safety_checks` lists the (side, height) pairs whose `withdrawal: safe` claim geometry's defects gate must verify. `convention_exempt` names the sides ("entry"/"exit") whose declared row carries `x_off_convention`, so E-ANCHOR skips that side and that side only."""

    cell: CellId
    bitmap: str | None = None
    entry_x: int | None = None
    exit_x: int | None = None
    entry_stub: Stub | None = None
    exit_stub: Stub | None = None
    entry_curs_only: tuple[int, int] | None = None  # selectable: false anchor kept for GPOS parity
    exit_ink_y: int | None = None
    convention_exempt: tuple[str, ...] = ()
    safety_checks: tuple[tuple[str, Height], ...] = ()
    unlock: Unlock | None = None  # set when the cell exists only via this unlock row

    @property
    def needs_safety_check(self) -> bool:
        return bool(self.safety_checks)


@dataclass(frozen=True)
class GlyphRecord:
    """geometry.realize's output: one compiled glyph. Anchors are (x, y) in glyph-space pixels; `name` is the generated display name (≤ 63 bytes, hash overflow), never parsed back."""

    name: str
    bitmap: tuple[str, ...]
    y_offset: int = 0
    entry: tuple[int, int] | None = None
    exit: tuple[int, int] | None = None
    entry_curs_only: tuple[int, int] | None = None
    advance_width: int | None = None
    exit_ink_y: int | None = None
    convention_exempt: tuple[str, ...] = ()  # sides exempt from E-ANCHOR ("entry"/"exit")
    safety_checks: tuple[tuple[str, Height], ...] = ()
    provenance: str = ""


Adjustment = (
    tuple[Literal["locked"], None, None]
    | tuple[Literal["ext", "con", "trim"], str, int]
    | tuple[Literal["bind"], str, str]
)


def parse_adjustment(token: str) -> Adjustment:
    """Split an adjustments token into (operation, side, argument): ("locked", None, None), ("ext", "en", 1), ("bind", "ex", "pulled-back-stubless"). The return is a union discriminated on the operation, so a caller that rules out "locked" gets a non-optional side."""
    if token == "locked":
        return ("locked", None, None)
    side, _, rest = token.partition("-")
    if side not in ("en", "ex") or not rest:
        raise ValueError(f"unrecognized adjustments token: {token!r}")
    op, _, argument = rest.partition("-")
    if op in ("ext", "con", "trim"):
        return (op, side, int(argument))
    if op == "bind":
        return ("bind", side, argument)
    raise ValueError(f"unrecognized adjustments token: {token!r}")


def feature_config_token(features: Collection[str]) -> str:
    enabled = sorted(features)
    return "+".join(enabled) if enabled else "default"


def relevant_marker_features(rune: Rune) -> tuple[str, ...]:
    """The stylistic sets that change this rune's own capability (its unlock rows) — the sets the rune carries marker twins for. Policy records gated on a feature observe the neighbor's marker instead and add nothing here (the prototype's qsMay finding)."""
    features: set[str] = set()
    for stance in rune.stances.values():
        for unlock in stance.surface.unlocks:
            features.add(unlock.feature)
    return tuple(sorted(features))


def marker_glyph_name(rune_name: str, active: Collection[str]) -> str:
    """The marker-twin display name for a rune under the given active relevant features; the bare name when none are active. Composite markers render multi-set union states (ss02+ss03 → qsTea.ss02_ss03)."""
    enabled = sorted(active)
    if not enabled:
        return rune_name
    return f"{rune_name}.{'_'.join(enabled)}"


def locked_glyph_name(raw_name: str) -> str:
    """The ZWNJ chokepoint twin's display name for a raw input glyph (bare rune or marker twin)."""
    return f"{raw_name}.noentry"


def isolated_overlay_active(spec: ResolvedSpec, features: Collection[str]) -> bool:
    """Whether any active feature is a registered `overlay: isolated` taste set (ss10). Under one, the emitted font substitutes every letter's cmap glyph by its anchor-free `.ss10` twin before formation, so no ligature forms, nothing settles, and every seam is a break — there is no settlement table for such a configuration, and every consumer that would have settled under it answers the isolated stream instead (`settle.isolated_overlay_settled`)."""
    return any(
        spec.registry.features.get(feature) is not None
        and spec.registry.features[feature].overlay == "isolated"
        for feature in features
    )


SS10_TWIN_SUFFIX = ".ss10"


def ss10_twin_name(raw_name: str) -> str:
    """The ss10 isolated-input twin's display name for a letter's raw cmap glyph: drawn identically to the bare glyph but carrying no curs anchors and no cmap entry, and absent from every formation, marker, chokepoint, and settlement input, so substituting it before formation isolates the letter from the whole join pipeline — no ligature forms, nothing settles, and each letter keeps its own cluster."""
    return f"{raw_name}{SS10_TWIN_SUFFIX}"
